<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeDir Condition="'$(RuntimeDir)' == ''">$(MSBuildThisFileDirectory)../../../../android/assets/dotnet_bcl</RuntimeDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="$(RuntimeDir)/Mono*.dll" />
    <Reference Include="$(RuntimeDir)/0Harmony.dll" />
  </ItemGroup>
</Project>
