#!/usr/bin/env python3
"""Generate Android vector drawables from the bundled Material Symbols font.

The launcher uses these generated vectors at runtime instead of drawing text
ligatures. This keeps the official Material Symbols shapes while avoiding ROM
font/ligature compatibility issues.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from xml.sax.saxutils import escape

try:
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.pens.transformPen import TransformPen
    from fontTools.ttLib import TTFont
except ImportError as exc:  # pragma: no cover - exercised by humans without fonttools
    raise SystemExit(
        "Missing dependency: fontTools. Install with `python3 -m pip install --user fonttools` "
        "or run the script from a venv that has fonttools installed."
    ) from exc

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_FONT = ROOT / "android/res/font/material_symbols_rounded.ttf"
DEFAULT_OUT_DIR = ROOT / "android/res/drawable"
DEFAULT_JAVA = ROOT / "android/src/com/godot/game/MaterialSymbols.java"
DEFAULT_SIZE = 24
DEFAULT_FONT_UNITS = 960

STATIC_GLYPHS = [
    "block",
    "cloud_done",
    "gamepad",
    "login",
    "play_arrow",
    "unarchive",
]

GLYPH_NAME_PATTERNS = [
    re.compile(r'return\s+"([a-z0-9_]+)"'),
    re.compile(r'"([a-z0-9_]+)"\.equals\(glyph\)'),
]

HEADER = "Generated by tools/android/generate-material-symbol-vectors.py from material_symbols_rounded.ttf."


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", type=Path, default=DEFAULT_FONT, help="Material Symbols TTF file")
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR, help="Android drawable output directory")
    parser.add_argument("--java", type=Path, default=DEFAULT_JAVA, help="MaterialSymbols.java for glyph list discovery")
    parser.add_argument("--glyph", action="append", default=[], help="Additional glyph ligature/name to generate")
    parser.add_argument("--check", action="store_true", help="Fail if generated files differ")
    return parser.parse_args()


def glyphs_from_java(path: Path) -> list[str]:
    if not path.is_file():
        raise SystemExit(f"MaterialSymbols.java not found: {path}")
    text = path.read_text(encoding="utf-8")
    names: set[str] = set()
    for pattern in GLYPH_NAME_PATTERNS:
        names.update(pattern.findall(text))
    return sorted(names)


def glyph_filename(name: str) -> str:
    safe = re.sub(r"[^a-z0-9_]+", "_", name.lower()).strip("_")
    if not safe:
        raise ValueError(f"Invalid glyph name: {name!r}")
    return f"ic_ms_{safe}_{DEFAULT_SIZE}.xml"


def decode_gsub_component(name: str) -> str:
    digits = {
        "zero": "0",
        "one": "1",
        "two": "2",
        "three": "3",
        "four": "4",
        "five": "5",
        "six": "6",
        "seven": "7",
        "eight": "8",
        "nine": "9",
    }
    if name == "underscore":
        return "_"
    if name == "hyphen":
        return "-"
    if name.startswith("digit_"):
        return digits.get(name.removeprefix("digit_"), "")
    if len(name) == 1:
        return name
    if name.startswith("uni") and len(name) == 7:
        try:
            return chr(int(name[3:], 16))
        except ValueError:
            return ""
    return ""


def build_ligature_map(font: TTFont) -> dict[str, str]:
    mapping: dict[str, str] = {}
    if "GSUB" not in font:
        return mapping
    lookup_list = font["GSUB"].table.LookupList
    if lookup_list is None:
        return mapping
    for lookup in lookup_list.Lookup:
        for subtable in lookup.SubTable:
            if getattr(subtable, "ExtensionLookupType", None):
                subtable = subtable.ExtSubTable
            ligatures = getattr(subtable, "ligatures", None)
            if not ligatures:
                continue
            for first, ligature_set in ligatures.items():
                for ligature in ligature_set:
                    components = [first] + list(ligature.Component)
                    text = "".join(decode_gsub_component(component) for component in components)
                    if text:
                        mapping[text] = ligature.LigGlyph
    return mapping


def resolve_glyph(font: TTFont, ligature_map: dict[str, str], name: str) -> str:
    glyph = ligature_map.get(name)
    if glyph:
        return glyph
    if name in font.getGlyphOrder():
        return name
    raise KeyError(name)


def path_for_glyph(font: TTFont, glyph_name: str) -> str:
    glyph_set = font.getGlyphSet()
    if glyph_name not in glyph_set:
        raise KeyError(glyph_name)
    pen = SVGPathPen(glyph_set)
    transform_pen = TransformPen(pen, (1, 0, 0, -1, 0, DEFAULT_FONT_UNITS))
    glyph_set[glyph_name].draw(transform_pen)
    return pen.getCommands()


def vector_xml(source_name: str, glyph_name: str, path_data: str) -> str:
    if not path_data:
        path_data = "M0 0"
    return """<?xml version=\"1.0\" encoding=\"utf-8\"?>
<!-- {header} Source glyph: {source} -> {glyph}. -->
<vector xmlns:android=\"http://schemas.android.com/apk/res/android\"
    android:width=\"24dp\"
    android:height=\"24dp\"
    android:viewportWidth=\"{units}\"
    android:viewportHeight=\"{units}\">
    <path
        android:fillColor=\"#FFFFFFFF\"
        android:pathData=\"{path}\" />
</vector>
""".format(
        header=escape(HEADER),
        source=escape(source_name),
        glyph=escape(glyph_name),
        units=DEFAULT_FONT_UNITS,
        path=escape(path_data),
    )


def write_or_check(path: Path, content: str, check: bool) -> bool:
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old == content:
        return False
    if check:
        print(f"out of date: {path}", file=sys.stderr)
        return True
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path}")
    return True


def main() -> int:
    args = parse_args()
    font_path = args.font.resolve()
    out_dir = args.out_dir.resolve()
    font = TTFont(font_path)
    ligature_map = build_ligature_map(font)
    glyphs = sorted(set(glyphs_from_java(args.java.resolve()) + STATIC_GLYPHS + args.glyph))
    out_dir.mkdir(parents=True, exist_ok=True)

    changed = False
    missing: list[str] = []
    for name in glyphs:
        try:
            glyph_name = resolve_glyph(font, ligature_map, name)
            path_data = path_for_glyph(font, glyph_name)
        except KeyError:
            missing.append(name)
            continue
        content = vector_xml(name, glyph_name, path_data)
        changed = write_or_check(out_dir / glyph_filename(name), content, args.check) or changed

    if missing:
        print("Missing Material Symbols glyphs: " + ", ".join(missing), file=sys.stderr)
        return 2
    if args.check and changed:
        return 1
    print(f"Material Symbols vectors {'checked' if args.check else 'generated'}: {len(glyphs)} file(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
